# Generated by Django 2.1.3 on 2018-11-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(max_length=64)),
                ('name', models.CharField(default='', max_length=128)),
                ('brand', models.CharField(default='', max_length=256)),
                ('retailer', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('price', models.DecimalField(decimal_places=2, default='0', max_digits=10)),
                ('in_stock', models.BooleanField(default=False)),
                ('source', models.IntegerField(choices=[(1, 'CSV'), (2, 'JSON'), (3, 'XML')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
                ('compression', models.IntegerField(choices=[(1, 'None'), (2, 'GZ'), (3, 'ZIP')], default=1)),
                ('format', models.IntegerField(choices=[(1, 'CSV'), (2, 'JSON'), (3, 'XML')], default=1)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('ext_id', 'name')},
        ),
    ]
