# Generated by Django 2.1.3 2018-11-21 21:27
from django.db import migrations




def load_sources(apps, schema_editor):
    data = [
        ('https://s3-eu-west-1.amazonaws.com/pricesearcher-code-tests/python-software-developer/products.csv.gz',
            2, 1),
        ('https://s3-eu-west-1.amazonaws.com/pricesearcher-code-tests/python-software-developer/products.json',
            1, 2),
        ('https://s3-eu-west-1.amazonaws.com/pricesearcher-code-tests/python-software-developer/products.xml.zip',
            3, 3)
    ]

    Source = apps.get_model('products', 'Source')
    for entry in data:
        Source.objects.create(url=entry[0], compression=entry[1], format=entry[2])


def clean_source(apps, shcema_editor):
    Source = apps.get_model('products', 'Source')
    sources = Source.objects.all()
    sources.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_sources, clean_source),
    ]
